# Generated by Django 3.0.2 on 2020-02-06 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='even_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='event_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='start_date',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_type',
        ),
    ]
